name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Copiar Configurações .env
      run: |
        cp contrib/env-sample .env

    - name: Before Scripts
      run: |
        psql -c "CREATE DATABASE testdb;" -U postgres

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync -d

    - name: Lint with flake8
      run: |
        pipenv run flake8

    - name: Teste de código com pytest
      run: |
        pipenv run pytest --cov=pypro
        
        

