name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        #pip install -r requirements-dev.txt
        pip install pipenv
        pipenv sync -d
        cp contrib/env-sample .env
    - name: Lint with flake8
      run: |

        pipenv run flake8
    - name: Teste de código com pytest
      run: |
        pipenv run pytest --cov=pypro
        
        

