name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.9
      uses: actions/setup-python@v1

    - name: Copiar Configurações .env
      run: |
        cp contrib/env-sample .env

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync -d

    - name: Lint with flake8
      run: |
        pipenv run flake8

    - name: Teste de código com pytest
      run: |
        pipenv run pytest --cov=pypro
        
        

